ci:
    autofix_prs: false


repos:
# there are some other useful hooks we could enable from here in the future
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-executables-have-shebangs
  - id: check-case-conflict # make sure no filenames would conflict on
                            # case-insensitive filesystems
  # these hooks check that .toml and .yaml files have valid syntax
  - id: check-toml
  - id: check-yaml

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.15
  hooks:
  # run the linter
  - id: ruff-check
    types_or: [ python ] # <- (consider adding jupyter to the list)
    args: [--fix, "--show-fixes"]
  # run the formatter
  - id: ruff-format
    types_or: [ python ] # <- (consider adding jupyter to the list)
