[build-system]
# here we specify the build-backend. For context:
# - tools like pip and uv are example of build-frontends. Users directly
#   interact with the frontend
# - tools like setuptools, hatchling, scikit-build-core, meson-python are all
#   examples of build backends
requires = [
    # the version bound is recommended in the docs
    "flit_core >=3.11,<4"
]
build-backend = "flit_core.buildapi"

[project]
name = "pah_spec"
license = "MIT"
license-files = ["LICENSE"]
# detect the version number from the __version__ variable in _version.py
dynamic = ["version"]
# we may need to adjust the version bounds
requires-python = ">=3.9"
description = "tool for generating PAH spectra with the single photon approximation"
readme = "README.md"
authors = [{name = "Helena Richie", email = "helenarichie@gmail.com"}]
# we should probably add version bounds
dependencies = [
  'astropy',
  'numpy',
  'pandas',
  'scipy >= 1.6.0',
  'h5py',
  # we may need to bumpy the lower limit
  'pooch >= 1.1, <2'
]

[project.urls]
Homepage = 'https://github.com/helenarichie/pah_spec'
Documentation = 'https://pah-spec.readthedocs.io/'
Source = 'https://github.com/helenarichie/pah_spec'
Tracker = 'https://github.com/helenarichie/pah_spec/issues'

[dependency-groups]
# these are development dependencies. They can be installed with pip (v25.1+)
# by invoking `pip install --user --group dev` from the directory holding this
# configuration file
docs = [
    'myst_parser',
    'sphinx',
    'sphinx_inline_tabs',
    'sphinx_rtd_theme'
]
test = ["pytest"]
dev = [{include-group = "docs"}, {include-group = "test"}]

# configure pytest
[tool.pytest.ini_options]
# settings inspired by: learn.scientific-python.org/development/guides/pytest/
#  -ra: The -r tells pytest to report extra test summary info on the events
#       corresponding to all characters following the r. Here, the "a"
#       corresponds to "all" events (other than passing tests)
#  --showlocals: directs pytest to show local variables in tracebacks
#  --strict-markers: ensures we don't try to use an unspecified fixture
#  --string-config: all configuration mistakes are reported as errors
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
# by default, we treat any test marked xfail that doesn't fail as an error
# (we can override this locally, if necessary)
xfail_strict = true
# limit the directories searched by pytests for the test files
testpaths = [
  "tests",
]
