name: Run Tests

on:
  push:
    branches: [main, kute]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install astropy scipy numpy pandas scipy requests

      - name: Run tests
        run: python -m unittest discover -s code/testing -p "pah_spec_test.py"