name: Run Tests

on:
  push:
    branches: [main, kute]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # the "-e" flag instructs the package to be installed in editable mode
      - name: Install pah_spec package
        run: pip install -e .

      - name: Install testing dependencies
        run: pip install --group test

      - name: Run tests
        run: pytest
